//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace internosSennaf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dependencia_Area
    {
        public int id { get; set; }
        public Nullable<int> idDependencia { get; set; }
        public Nullable<int> idArea { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Dependencia Dependencia { get; set; }
    }
}
