//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace internosSennaf.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class internosSenafEntities : DbContext
    {
        public internosSenafEntities()
            : base("name=internosSenafEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Contacto> Contacto { get; set; }
        public virtual DbSet<Dependencia> Dependencia { get; set; }
        public virtual DbSet<Dependencia_Area> Dependencia_Area { get; set; }
        public virtual DbSet<Interno> Interno { get; set; }
        public virtual DbSet<Interno_Puesto> Interno_Puesto { get; set; }
        public virtual DbSet<Piso> Piso { get; set; }
        public virtual DbSet<Puesto> Puesto { get; set; }
        public virtual DbSet<Sector> Sector { get; set; }
        public virtual DbSet<Sector_Piso> Sector_Piso { get; set; }
    }
}
