//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace internosSennaf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sector_Piso
    {
        public int id { get; set; }
        public Nullable<int> idPiso { get; set; }
        public Nullable<int> idSector { get; set; }
    
        public virtual Piso Piso { get; set; }
        public virtual Sector Sector { get; set; }
    }
}
